-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- TBL_USER Table Create SQL
CREATE TABLE TBL_USER
(
    U_PK            INT             NOT NULL,
    U_ID            VARCHAR2(20)    NOT NULL,
    U_PW            VARCHAR2(20)    NOT NULL,
    U_NAME          VARCHAR2(20)    NOT NULL,
    U_EMAIL         VARCHAR2(20)    NOT NULL,
    U_REGDATE       DATE            DEFAULT SYSDATE NOT NULL,
    U_UPDATEDATE    DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TBL_USER_PK PRIMARY KEY (U_PK)
)
/

CREATE SEQUENCE TBL_USER_SEQ
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TBL_USER_AI_TRG
    BEFORE INSERT ON TBL_USER
    REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
    SELECT TBL_USER_SEQ.NEXTVAL
    INTO :NEW.U_PK
    FROM DUAL;
END;
/

--DROP TRIGGER TBL_USER_AI_TRG;
/

--DROP SEQUENCE TBL_USER_SEQ;
/


-- TBL_USER Table Create SQL
CREATE TABLE TBL_FIELD
(
    F_PK            INT             NOT NULL,
    U_PK            INT             NOT NULL,
    F_NAME          VARCHAR2(20)    NOT NULL,
    F_RATIO         NUMBER          NOT NULL,
    F_REGDATE       DATE            DEFAULT SYSDATE NOT NULL,
    F_UPDATEDATE    DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TBL_FIELD_PK PRIMARY KEY (F_PK)
)
/

CREATE SEQUENCE TBL_FIELD_SEQ
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TBL_FIELD_AI_TRG
    BEFORE INSERT ON TBL_FIELD
    REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
    SELECT TBL_FIELD_SEQ.NEXTVAL
    INTO :NEW.F_PK
    FROM DUAL;
END;
/

--DROP TRIGGER TBL_FIELD_AI_TRG;
/

--DROP SEQUENCE TBL_FIELD_SEQ;
/

ALTER TABLE TBL_FIELD
    ADD CONSTRAINT FK_TBL_FIELD_U_PK_TBL_USER_U_P FOREIGN KEY (U_PK)
        REFERENCES TBL_USER (U_PK)
/


-- TBL_USER Table Create SQL
CREATE TABLE TBL_COUNTRY
(
    C_PK            INT             NOT NULL,
    U_PK            INT             NOT NULL,
    C_NAME          VARCHAR2(20)    NOT NULL,
    C_RATIO         NUMBER          NOT NULL,
    C_REGDATE       DATE            DEFAULT SYSDATE NOT NULL,
    C_UPDATEDATE    DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TBL_COUNTRY_PK PRIMARY KEY (C_PK)
)
/

CREATE SEQUENCE TBL_COUNTRY_SEQ
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TBL_COUNTRY_AI_TRG
    BEFORE INSERT ON TBL_COUNTRY
    REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
    SELECT TBL_COUNTRY_SEQ.NEXTVAL
    INTO :NEW.C_PK
    FROM DUAL;
END;
/

--DROP TRIGGER TBL_COUNTRY_AI_TRG;
/

--DROP SEQUENCE TBL_COUNTRY_SEQ;
/

ALTER TABLE TBL_COUNTRY
    ADD CONSTRAINT FK_TBL_COUNTRY_U_PK_TBL_USER_U FOREIGN KEY (U_PK)
        REFERENCES TBL_USER (U_PK)
/


-- TBL_USER Table Create SQL
CREATE TABLE TBL_STOCK
(
    S_PK            INT             NOT NULL,
    U_PK            INT             NOT NULL,
    F_PK            INT             NOT NULL,
    C_PK            INT             NOT NULL,
    S_NAME          VARCHAR2(20)    NOT NULL,
    S_PRICE         NUMBER          NOT NULL,
    S_NUM           INT             NOT NULL,
    S_REGDATE       DATE            DEFAULT SYSDATE NOT NULL,
    S_UPDATEDATE    DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TBL_STOCK_PK PRIMARY KEY (S_PK)
)
/

CREATE SEQUENCE TBL_STOCK_SEQ
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TBL_STOCK_AI_TRG
    BEFORE INSERT ON TBL_STOCK
    REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
    SELECT TBL_STOCK_SEQ.NEXTVAL
    INTO :NEW.S_PK
    FROM DUAL;
END;
/

--DROP TRIGGER TBL_STOCK_AI_TRG;
/

--DROP SEQUENCE TBL_STOCK_SEQ;
/

ALTER TABLE TBL_STOCK
    ADD CONSTRAINT FK_TBL_STOCK_U_PK_TBL_USER_U_P FOREIGN KEY (U_PK)
        REFERENCES TBL_USER (U_PK)
/

ALTER TABLE TBL_STOCK
    ADD CONSTRAINT FK_TBL_STOCK_F_PK_TBL_FIELD_F_ FOREIGN KEY (F_PK)
        REFERENCES TBL_FIELD (F_PK)
/

ALTER TABLE TBL_STOCK
    ADD CONSTRAINT FK_TBL_STOCK_C_PK_TBL_COUNTRY_ FOREIGN KEY (C_PK)
        REFERENCES TBL_COUNTRY (C_PK)
/


