-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- USER Table Create SQL
CREATE TABLE USER
(
    U_PK       INT             NOT NULL,
    U_ID       VARCHAR2(20)    NOT NULL,
    U_PW       VARCHAR2(20)    NOT NULL,
    U_NAME     VARCHAR2(20)    NOT NULL,
    U_EMAIL    VARCHAR2(20)    NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (U_PK)
)
    /

CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER USER_AI_TRG
BEFORE INSERT ON USER
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
SELECT USER_SEQ.NEXTVAL
INTO :NEW.U_PK
FROM DUAL;
END;
/

--DROP TRIGGER USER_AI_TRG;
/

--DROP SEQUENCE USER_SEQ;
/


-- USER Table Create SQL
CREATE TABLE FIELD
(
    F_PK       INT             NOT NULL,
    U_PK       INT             NOT NULL,
    F_NAME     VARCHAR2(20)    NOT NULL,
    F_RATIO    NUMBER          NOT NULL,
    CONSTRAINT FIELD_PK PRIMARY KEY (F_PK)
)
    /

CREATE SEQUENCE FIELD_SEQ
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER FIELD_AI_TRG
BEFORE INSERT ON FIELD
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
SELECT FIELD_SEQ.NEXTVAL
INTO :NEW.F_PK
FROM DUAL;
END;
/

--DROP TRIGGER FIELD_AI_TRG;
/

--DROP SEQUENCE FIELD_SEQ;
/

ALTER TABLE FIELD
    ADD CONSTRAINT FK_FIELD_U_PK_USER_U_PK FOREIGN KEY (U_PK)
        REFERENCES USER (U_PK)
    /


-- USER Table Create SQL
CREATE TABLE COUNTRY
(
    C_PK       INT             NOT NULL,
    U_PK       INT             NOT NULL,
    C_NAME     VARCHAR2(20)    NOT NULL,
    C_RATIO    NUMBER          NOT NULL,
    CONSTRAINT COUNTRY_PK PRIMARY KEY (C_PK)
)
    /

CREATE SEQUENCE COUNTRY_SEQ
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER COUNTRY_AI_TRG
BEFORE INSERT ON COUNTRY
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
SELECT COUNTRY_SEQ.NEXTVAL
INTO :NEW.C_PK
FROM DUAL;
END;
/

--DROP TRIGGER COUNTRY_AI_TRG;
/

--DROP SEQUENCE COUNTRY_SEQ;
/

ALTER TABLE COUNTRY
    ADD CONSTRAINT FK_COUNTRY_U_PK_USER_U_PK FOREIGN KEY (U_PK)
        REFERENCES USER (U_PK)
    /


-- USER Table Create SQL
CREATE TABLE STOCK
(
    S_PK       INT             NOT NULL,
    U_PK       INT             NOT NULL,
    F_PK       INT             NOT NULL,
    C_PK       INT             NOT NULL,
    S_NAME     VARCHAR2(20)    NOT NULL,
    S_PRICE    NUMBER          NOT NULL,
    S_NUM      INT             NOT NULL,
    CONSTRAINT STOCK_PK PRIMARY KEY (S_PK)
)
    /

CREATE SEQUENCE STOCK_SEQ
    START WITH 1
    INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER STOCK_AI_TRG
BEFORE INSERT ON STOCK
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
SELECT STOCK_SEQ.NEXTVAL
INTO :NEW.S_PK
FROM DUAL;
END;
/

--DROP TRIGGER STOCK_AI_TRG;
/

--DROP SEQUENCE STOCK_SEQ;
/

ALTER TABLE STOCK
    ADD CONSTRAINT FK_STOCK_U_PK_USER_U_PK FOREIGN KEY (U_PK)
        REFERENCES USER (U_PK)
    /

ALTER TABLE STOCK
    ADD CONSTRAINT FK_STOCK_F_PK_FIELD_F_PK FOREIGN KEY (F_PK)
        REFERENCES FIELD (F_PK)
    /

ALTER TABLE STOCK
    ADD CONSTRAINT FK_STOCK_C_PK_COUNTRY_C_PK FOREIGN KEY (C_PK)
        REFERENCES COUNTRY (C_PK)
    /


