CREATE OR REPLACE TRIGGER TBL_USER_AI_TRG
BEFORE INSERT ON TBL_USER
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TBL_USER_SEQ.NEXTVAL
    INTO :NEW.U_NO
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TBL_ASSET_AI_TRG
BEFORE INSERT ON TBL_ASSET 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TBL_ASSET_SEQ.NEXTVAL
    INTO :NEW.A_NO
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TBL_COUNTRY_AI_TRG
BEFORE INSERT ON TBL_COUNTRY 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TBL_COUNTRY_SEQ.NEXTVAL
    INTO :NEW.C_NO
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TBL_INVESTMENT_AI_TRG
BEFORE INSERT ON TBL_INVESTMENT 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TBL_INVESTMENT_SEQ.NEXTVAL
    INTO :NEW.I_NO
    FROM DUAL;
END;
/